-- Sales contract backend moved into the active management Supabase project.
-- Source: AtsushiSora/hanbai-keiyakusho schema and follow-up migrations.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.order_auto_contracts (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  buyer_name text,
  buyer_email text,
  vehicle_name text,
  total_price text,
  status text not null default '下書き',
  document_type text not null default '契約書',
  data jsonb not null default '{}'::jsonb,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.order_auto_contracts
  add column if not exists buyer_email text,
  add column if not exists document_type text not null default '契約書',
  add column if not exists completed_at timestamptz,
  add column if not exists customer_pdf_path text,
  add column if not exists download_access_hash text,
  add column if not exists download_access_expires_at timestamptz,
  add column if not exists reviewed_at timestamptz,
  add column if not exists customer_confirmation_sent_at timestamptz,
  add column if not exists confirmation_email_status text;

create table if not exists public.order_auto_document_counters (
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  issue_date date not null,
  last_value integer not null default 0 check (last_value between 0 and 99),
  updated_at timestamptz not null default now(),
  primary key (owner_user_id, issue_date)
);

create table if not exists public.order_auto_remote_contracts (
  id uuid primary key default gen_random_uuid(),
  contract_id text not null references public.order_auto_contracts(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  access_token_hash bytea not null unique,
  passcode_hash text not null,
  contract_data jsonb not null,
  status text not null default '送信済み',
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  locked_until timestamptz,
  expires_at timestamptz not null,
  opened_at timestamptz,
  completed_at timestamptz,
  signer_name text,
  consent_items jsonb not null default '[]'::jsonb,
  signature_data_url text,
  customer_pdf_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.order_auto_remote_contracts
  add column if not exists customer_pdf_path text;

create table if not exists public.order_auto_remote_events (
  id bigint generated by default as identity primary key,
  remote_contract_id uuid not null references public.order_auto_remote_contracts(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.order_auto_admin_notifications (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  notification_type text not null default 'contract',
  title text not null,
  message text not null,
  payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace function public.set_order_auto_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists order_auto_contracts_set_updated_at on public.order_auto_contracts;
create trigger order_auto_contracts_set_updated_at
before update on public.order_auto_contracts
for each row execute function public.set_order_auto_updated_at();

drop trigger if exists order_auto_remote_contracts_set_updated_at on public.order_auto_remote_contracts;
create trigger order_auto_remote_contracts_set_updated_at
before update on public.order_auto_remote_contracts
for each row execute function public.set_order_auto_updated_at();

create or replace function public.lock_submitted_order_auto_remote_link()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status = '確認待ち' and old.status is distinct from new.status then
    new.expires_at = least(new.expires_at, now());
  end if;
  return new;
end;
$$;

drop trigger if exists order_auto_remote_contracts_lock_submitted_link
on public.order_auto_remote_contracts;
create trigger order_auto_remote_contracts_lock_submitted_link
before update of status on public.order_auto_remote_contracts
for each row execute function public.lock_submitted_order_auto_remote_link();

alter table public.order_auto_contracts enable row level security;
alter table public.order_auto_document_counters enable row level security;
alter table public.order_auto_remote_contracts enable row level security;
alter table public.order_auto_remote_events enable row level security;
alter table public.order_auto_admin_notifications enable row level security;

drop policy if exists "order_auto_contracts_select_own" on public.order_auto_contracts;
drop policy if exists "order_auto_contracts_insert_own" on public.order_auto_contracts;
drop policy if exists "order_auto_contracts_update_own" on public.order_auto_contracts;
drop policy if exists "order_auto_contracts_delete_own" on public.order_auto_contracts;

create policy "order_auto_contracts_select_own"
on public.order_auto_contracts
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "order_auto_contracts_insert_own"
on public.order_auto_contracts
for insert
to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "order_auto_contracts_update_own"
on public.order_auto_contracts
for update
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "order_auto_contracts_delete_own"
on public.order_auto_contracts
for delete
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

drop policy if exists "order_auto_remote_contracts_select_own" on public.order_auto_remote_contracts;
drop policy if exists "order_auto_remote_contracts_delete_own" on public.order_auto_remote_contracts;

create policy "order_auto_remote_contracts_select_own"
on public.order_auto_remote_contracts
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_user_id);

create policy "order_auto_remote_contracts_delete_own"
on public.order_auto_remote_contracts
for delete
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_user_id);

drop policy if exists "order_auto_remote_events_select_own" on public.order_auto_remote_events;

create policy "order_auto_remote_events_select_own"
on public.order_auto_remote_events
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_user_id);

drop policy if exists "order_auto_admin_notifications_select_own" on public.order_auto_admin_notifications;
drop policy if exists "order_auto_admin_notifications_update_own" on public.order_auto_admin_notifications;
drop policy if exists "order_auto_admin_notifications_delete_own" on public.order_auto_admin_notifications;

create policy "order_auto_admin_notifications_select_own"
on public.order_auto_admin_notifications
for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_user_id);

create policy "order_auto_admin_notifications_update_own"
on public.order_auto_admin_notifications
for update
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_user_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = owner_user_id);

create policy "order_auto_admin_notifications_delete_own"
on public.order_auto_admin_notifications
for delete
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = owner_user_id);

create index if not exists order_auto_contracts_user_updated_idx
on public.order_auto_contracts (user_id, updated_at desc);

create unique index if not exists order_auto_contracts_download_access_hash_key
on public.order_auto_contracts (download_access_hash)
where download_access_hash is not null;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'order-auto-contract-files',
  'order-auto-contract-files',
  false,
  15728640,
  array['application/pdf']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.save_order_auto_contract(
  p_id text,
  p_buyer_name text,
  p_buyer_email text,
  p_vehicle_name text,
  p_total_price text,
  p_status text,
  p_document_type text,
  p_data jsonb
)
returns setof public.order_auto_contracts
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_existing public.order_auto_contracts%rowtype;
  v_exists boolean := false;
  v_issue_date date := (now() at time zone 'Asia/Tokyo')::date;
  v_sequence integer;
  v_document_number text;
  v_data jsonb := coalesce(p_data, '{}'::jsonb);
begin
  if v_user_id is null
    or p_id is null
    or p_id !~ '^[A-Za-z0-9_-]{1,120}$' then
    return;
  end if;

  select * into v_existing
  from public.order_auto_contracts
  where id = p_id and user_id = v_user_id
  for update;
  v_exists := found;

  if v_exists and btrim(coalesce(v_existing.data->>'estimateNo', '')) <> '' then
    v_document_number := v_existing.data->>'estimateNo';
  else
    insert into public.order_auto_document_counters (
      owner_user_id,
      issue_date,
      last_value,
      updated_at
    ) values (
      v_user_id,
      v_issue_date,
      1,
      now()
    )
    on conflict (owner_user_id, issue_date)
    do update set
      last_value = public.order_auto_document_counters.last_value + 1,
      updated_at = now()
    returning last_value into v_sequence;

    if v_sequence > 99 then
      raise exception 'Daily document number limit exceeded';
    end if;

    v_document_number := to_char(v_issue_date, 'YYMMDD') || lpad(v_sequence::text, 2, '0');
  end if;

  v_data := jsonb_set(v_data, '{estimateNo}', to_jsonb(v_document_number), true);

  if v_exists then
    update public.order_auto_contracts
    set
      buyer_name = p_buyer_name,
      buyer_email = p_buyer_email,
      vehicle_name = p_vehicle_name,
      total_price = p_total_price,
      status = coalesce(nullif(p_status, ''), '下書き'),
      document_type = coalesce(nullif(p_document_type, ''), '契約書'),
      data = v_data
    where id = p_id and user_id = v_user_id;
  else
    insert into public.order_auto_contracts (
      id,
      user_id,
      buyer_name,
      buyer_email,
      vehicle_name,
      total_price,
      status,
      document_type,
      data
    ) values (
      p_id,
      v_user_id,
      p_buyer_name,
      p_buyer_email,
      p_vehicle_name,
      p_total_price,
      coalesce(nullif(p_status, ''), '下書き'),
      coalesce(nullif(p_document_type, ''), '契約書'),
      v_data
    );
  end if;

  return query
  select * from public.order_auto_contracts
  where id = p_id and user_id = v_user_id;
end;
$$;

create index if not exists order_auto_remote_contracts_owner_updated_idx
on public.order_auto_remote_contracts (owner_user_id, updated_at desc);

create index if not exists order_auto_remote_contracts_contract_idx
on public.order_auto_remote_contracts (contract_id, created_at desc);

create index if not exists order_auto_remote_events_owner_created_idx
on public.order_auto_remote_events (owner_user_id, created_at desc);

create index if not exists order_auto_admin_notifications_owner_created_idx
on public.order_auto_admin_notifications (owner_user_id, created_at desc);

create or replace function public.create_order_auto_remote_contract(
  p_contract_id text,
  p_access_token text,
  p_passcode text,
  p_expires_at timestamptz
)
returns table(remote_id uuid, expires_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_contract public.order_auto_contracts%rowtype;
  v_remote public.order_auto_remote_contracts%rowtype;
begin
  if v_user_id is null then
    return;
  end if;
  if p_access_token is null
    or p_access_token !~ '^[A-Za-z0-9_-]{43,128}$'
    or p_passcode is null
    or p_passcode !~ '^[0-9]{8}$' then
    return;
  end if;
  if p_expires_at is null
    or p_expires_at <= now()
    or p_expires_at > now() + interval '30 days' then
    return;
  end if;

  select * into v_contract
  from public.order_auto_contracts
  where id = p_contract_id and user_id = v_user_id;

  if not found then
    return;
  end if;

  update public.order_auto_remote_contracts
  set status = '取消'
  where contract_id = p_contract_id
    and owner_user_id = v_user_id
    and status in ('送信済み', '開封済み');

  insert into public.order_auto_remote_contracts (
    contract_id,
    owner_user_id,
    access_token_hash,
    passcode_hash,
    contract_data,
    expires_at
  ) values (
    p_contract_id,
    v_user_id,
    extensions.digest(convert_to(p_access_token, 'UTF8'), 'sha256'),
    extensions.crypt(p_passcode, extensions.gen_salt('bf', 10)),
    v_contract.data,
    p_expires_at
  ) returning * into v_remote;

  update public.order_auto_contracts
  set
    status = '送信済み',
    data = jsonb_set(v_contract.data, '{remoteStatus}', '"送信済み"'::jsonb, true)
  where id = p_contract_id and user_id = v_user_id;

  insert into public.order_auto_remote_events (
    remote_contract_id,
    owner_user_id,
    event_type
  ) values (
    v_remote.id,
    v_user_id,
    'created'
  );

  return query select v_remote.id, v_remote.expires_at;
end;
$$;

create or replace function public.read_order_auto_remote_contract(
  p_access_token text,
  p_passcode text
)
returns table(
  remote_id uuid,
  contract_id text,
  contract_data jsonb,
  expires_at timestamptz,
  status text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_remote public.order_auto_remote_contracts%rowtype;
  v_now timestamptz := now();
  v_failed_attempts integer;
begin
  if p_access_token is null
    or p_access_token !~ '^[A-Za-z0-9_-]{43,128}$'
    or p_passcode is null
    or p_passcode !~ '^[0-9]{8}$' then
    return;
  end if;

  select * into v_remote
  from public.order_auto_remote_contracts
  where access_token_hash = extensions.digest(convert_to(p_access_token, 'UTF8'), 'sha256')
  for update;

  if not found
    or v_remote.status in ('完了', '取消')
    or v_remote.expires_at <= v_now
    or (v_remote.locked_until is not null and v_remote.locked_until > v_now) then
    return;
  end if;

  if extensions.crypt(p_passcode, v_remote.passcode_hash) <> v_remote.passcode_hash then
    v_failed_attempts := v_remote.failed_attempts + 1;
    update public.order_auto_remote_contracts
    set
      failed_attempts = v_failed_attempts,
      locked_until = case when v_failed_attempts >= 5 then v_now + interval '15 minutes' else null end
    where id = v_remote.id;

    insert into public.order_auto_remote_events (
      remote_contract_id,
      owner_user_id,
      event_type,
      metadata
    ) values (
      v_remote.id,
      v_remote.owner_user_id,
      'unlock_failed',
      jsonb_build_object('failed_attempts', v_failed_attempts)
    );
    return;
  end if;

  update public.order_auto_remote_contracts
  set
    status = '開封済み',
    opened_at = coalesce(opened_at, v_now),
    failed_attempts = 0,
    locked_until = null
  where id = v_remote.id;

  insert into public.order_auto_remote_events (
    remote_contract_id,
    owner_user_id,
    event_type
  ) values (
    v_remote.id,
    v_remote.owner_user_id,
    'opened'
  );

  return query
  select v_remote.id, v_remote.contract_id, v_remote.contract_data, v_remote.expires_at, '開封済み'::text;
end;
$$;

create or replace function public.complete_order_auto_remote_contract(
  p_access_token text,
  p_passcode text,
  p_signer_name text,
  p_consent_items jsonb,
  p_signature_data_url text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_remote public.order_auto_remote_contracts%rowtype;
  v_now timestamptz := now();
  v_clean_name text := btrim(p_signer_name);
begin
  if p_access_token is null
    or p_access_token !~ '^[A-Za-z0-9_-]{43,128}$'
    or p_passcode is null
    or p_passcode !~ '^[0-9]{8}$' then
    return false;
  end if;
  if v_clean_name is null or length(v_clean_name) < 1 or length(v_clean_name) > 120 then
    return false;
  end if;
  if p_consent_items is null
    or jsonb_typeof(p_consent_items) <> 'array'
    or jsonb_array_length(p_consent_items) < 1 then
    return false;
  end if;
  if p_signature_data_url is null
    or p_signature_data_url !~ '^data:image/png;base64,'
    or octet_length(p_signature_data_url) > 750000 then
    return false;
  end if;

  select * into v_remote
  from public.order_auto_remote_contracts
  where access_token_hash = extensions.digest(convert_to(p_access_token, 'UTF8'), 'sha256')
  for update;

  if not found
    or v_remote.status in ('完了', '取消')
    or v_remote.expires_at <= v_now
    or (v_remote.locked_until is not null and v_remote.locked_until > v_now)
    or extensions.crypt(p_passcode, v_remote.passcode_hash) <> v_remote.passcode_hash then
    return false;
  end if;

  update public.order_auto_remote_contracts
  set
    status = '完了',
    signer_name = v_clean_name,
    consent_items = p_consent_items,
    signature_data_url = p_signature_data_url,
    completed_at = v_now,
    failed_attempts = 0,
    locked_until = null
  where id = v_remote.id;

  update public.order_auto_contracts
  set
    status = '完了',
    completed_at = v_now,
    data = jsonb_set(
      jsonb_set(data, '{contractStatus}', '"完了"'::jsonb, true),
      '{remoteStatus}',
      '"完了"'::jsonb,
      true
    )
  where id = v_remote.contract_id and user_id = v_remote.owner_user_id;

  insert into public.order_auto_remote_events (
    remote_contract_id,
    owner_user_id,
    event_type,
    metadata
  ) values (
    v_remote.id,
    v_remote.owner_user_id,
    'completed',
    jsonb_build_object('signer_name', v_clean_name)
  );

  return true;
end;
$$;

create or replace function public.complete_order_auto_remote_contract_v2(
  p_access_token text,
  p_passcode text,
  p_signer_name text,
  p_consent_items jsonb,
  p_signature_data_url text,
  p_customer_data jsonb
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_remote public.order_auto_remote_contracts%rowtype;
  v_now timestamptz := now();
  v_clean_name text := btrim(coalesce(p_signer_name, ''));
  v_customer jsonb := coalesce(p_customer_data, '{}'::jsonb);
  v_clean_zip text;
  v_clean_phone text;
  v_clean_email text;
  v_contract_data jsonb;
begin
  if p_access_token is null
    or p_access_token !~ '^[A-Za-z0-9_-]{43,128}$'
    or p_passcode is null
    or p_passcode !~ '^[0-9]{8}$' then
    return false;
  end if;
  if jsonb_typeof(v_customer) <> 'object'
    or length(v_clean_name) < 1
    or length(v_clean_name) > 120 then
    return false;
  end if;

  v_clean_zip := regexp_replace(coalesce(v_customer->>'buyerZip', ''), '[^0-9]', '', 'g');
  v_clean_phone := regexp_replace(coalesce(v_customer->>'buyerPhone', ''), '[^0-9]', '', 'g');
  v_clean_email := btrim(coalesce(v_customer->>'buyerEmail', ''));

  if btrim(coalesce(v_customer->>'buyerAddress', '')) = ''
    or v_clean_zip !~ '^[0-9]{7}$'
    or v_clean_phone !~ '^[0-9]{10,11}$'
    or (v_clean_email <> '' and v_clean_email !~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$') then
    return false;
  end if;
  if p_consent_items is null
    or jsonb_typeof(p_consent_items) <> 'array'
    or jsonb_array_length(p_consent_items) < 1 then
    return false;
  end if;
  if p_signature_data_url is null
    or p_signature_data_url !~ '^data:image/png;base64,'
    or octet_length(p_signature_data_url) > 750000 then
    return false;
  end if;

  select * into v_remote
  from public.order_auto_remote_contracts
  where access_token_hash = extensions.digest(convert_to(p_access_token, 'UTF8'), 'sha256')
  for update;

  if not found
    or v_remote.status in ('完了', '取消')
    or v_remote.expires_at <= v_now
    or (v_remote.locked_until is not null and v_remote.locked_until > v_now)
    or extensions.crypt(p_passcode, v_remote.passcode_hash) <> v_remote.passcode_hash then
    return false;
  end if;

  v_customer := jsonb_build_object(
    'buyerName', v_clean_name,
    'buyerKana', left(btrim(coalesce(v_customer->>'buyerKana', '')), 120),
    'buyerBirthday', left(btrim(coalesce(v_customer->>'buyerBirthday', '')), 20),
    'buyerZip', substr(v_clean_zip, 1, 3) || '-' || substr(v_clean_zip, 4),
    'buyerAddress', left(btrim(v_customer->>'buyerAddress'), 300),
    'buyerPhone', left(btrim(v_customer->>'buyerPhone'), 30),
    'buyerEmail', left(v_clean_email, 254),
    'buyerWorkplace', left(btrim(coalesce(v_customer->>'buyerWorkplace', '')), 200)
  );
  v_contract_data := v_remote.contract_data || v_customer;

  update public.order_auto_remote_contracts
  set
    contract_data = v_contract_data,
    status = '完了',
    signer_name = v_clean_name,
    consent_items = p_consent_items,
    signature_data_url = p_signature_data_url,
    completed_at = v_now,
    failed_attempts = 0,
    locked_until = null
  where id = v_remote.id;

  update public.order_auto_contracts
  set
    buyer_name = v_clean_name,
    buyer_email = v_clean_email,
    status = '完了',
    completed_at = v_now,
    data = jsonb_set(
      jsonb_set(data || v_customer, '{contractStatus}', '"完了"'::jsonb, true),
      '{remoteStatus}',
      '"完了"'::jsonb,
      true
    )
  where id = v_remote.contract_id and user_id = v_remote.owner_user_id;

  insert into public.order_auto_remote_events (
    remote_contract_id,
    owner_user_id,
    event_type,
    metadata
  ) values (
    v_remote.id,
    v_remote.owner_user_id,
    'completed',
    jsonb_build_object('signer_name', v_clean_name, 'customer_entered', true)
  );

  insert into public.order_auto_admin_notifications (
    owner_user_id,
    notification_type,
    title,
    message,
    payload
  ) values (
    v_remote.owner_user_id,
    'remote_contract_completed',
    'メール・LINE契約が完了しました',
    v_clean_name || ' 様が契約内容を確認し、電子署名を完了しました。',
    jsonb_build_object(
      'contract_id', v_remote.contract_id,
      'remote_contract_id', v_remote.id,
      'signer_name', v_clean_name,
      'completed_at', v_now
    )
  );

  return true;
end;
$$;

create or replace function public.submit_order_auto_remote_contract_for_review(
  p_access_token text,
  p_passcode text,
  p_signer_name text,
  p_consent_items jsonb,
  p_signature_data_url text,
  p_customer_data jsonb
)
returns table(
  remote_id uuid,
  contract_id text,
  owner_user_id uuid,
  signed_at timestamptz,
  contract_number text,
  buyer_email text,
  contract_data jsonb
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_remote public.order_auto_remote_contracts%rowtype;
  v_now timestamptz := now();
  v_clean_name text := btrim(coalesce(p_signer_name, ''));
  v_customer jsonb := coalesce(p_customer_data, '{}'::jsonb);
  v_clean_zip text;
  v_clean_phone text;
  v_clean_email text;
  v_contract_data jsonb;
begin
  if p_access_token is null
    or p_access_token !~ '^[A-Za-z0-9_-]{43,128}$'
    or p_passcode is null
    or p_passcode !~ '^[0-9]{8}$' then
    return;
  end if;
  if jsonb_typeof(v_customer) <> 'object'
    or length(v_clean_name) < 1
    or length(v_clean_name) > 120 then
    return;
  end if;

  v_clean_zip := regexp_replace(coalesce(v_customer->>'buyerZip', ''), '[^0-9]', '', 'g');
  v_clean_phone := regexp_replace(coalesce(v_customer->>'buyerPhone', ''), '[^0-9]', '', 'g');
  v_clean_email := btrim(coalesce(v_customer->>'buyerEmail', ''));

  if btrim(coalesce(v_customer->>'buyerAddress', '')) = ''
    or v_clean_zip !~ '^[0-9]{7}$'
    or v_clean_phone !~ '^[0-9]{10,11}$'
    or v_clean_email !~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$' then
    return;
  end if;
  if p_consent_items is null
    or jsonb_typeof(p_consent_items) <> 'array'
    or jsonb_array_length(p_consent_items) < 1 then
    return;
  end if;
  if p_signature_data_url is null
    or p_signature_data_url !~ '^data:image/png;base64,'
    or octet_length(p_signature_data_url) > 750000 then
    return;
  end if;

  select * into v_remote
  from public.order_auto_remote_contracts as remote
  where remote.access_token_hash = extensions.digest(convert_to(p_access_token, 'UTF8'), 'sha256')
  for update;

  if not found
    or v_remote.status in ('完了', '確認待ち', '取消')
    or v_remote.expires_at <= v_now
    or (v_remote.locked_until is not null and v_remote.locked_until > v_now)
    or extensions.crypt(p_passcode, v_remote.passcode_hash) <> v_remote.passcode_hash then
    return;
  end if;

  v_customer := jsonb_build_object(
    'buyerLastName', left(btrim(coalesce(v_customer->>'buyerLastName', '')), 60),
    'buyerFirstName', left(btrim(coalesce(v_customer->>'buyerFirstName', '')), 60),
    'buyerName', v_clean_name,
    'buyerKana', left(btrim(coalesce(v_customer->>'buyerKana', '')), 120),
    'buyerBirthday', left(btrim(coalesce(v_customer->>'buyerBirthday', '')), 20),
    'buyerZip', substr(v_clean_zip, 1, 3) || '-' || substr(v_clean_zip, 4),
    'buyerAddress', left(btrim(v_customer->>'buyerAddress'), 300),
    'buyerPhone', left(btrim(v_customer->>'buyerPhone'), 30),
    'buyerEmail', left(v_clean_email, 254),
    'buyerWorkplace', left(btrim(coalesce(v_customer->>'buyerWorkplace', '')), 200)
  );
  v_contract_data := v_remote.contract_data || v_customer;

  update public.order_auto_remote_contracts
  set
    contract_data = v_contract_data,
    status = '確認待ち',
    signer_name = v_clean_name,
    consent_items = p_consent_items,
    signature_data_url = p_signature_data_url,
    completed_at = v_now,
    expires_at = v_now,
    customer_pdf_path = null,
    failed_attempts = 0,
    locked_until = null
  where id = v_remote.id;

  update public.order_auto_contracts
  set
    buyer_name = v_clean_name,
    buyer_email = v_clean_email,
    status = '確認待ち',
    completed_at = null,
    customer_pdf_path = null,
    download_access_hash = null,
    download_access_expires_at = null,
    reviewed_at = null,
    customer_confirmation_sent_at = null,
    confirmation_email_status = null,
    data = jsonb_set(
      jsonb_set(data || v_customer, '{contractStatus}', '"確認待ち"'::jsonb, true),
      '{remoteStatus}',
      '"確認待ち"'::jsonb,
      true
    )
  where id = v_remote.contract_id and user_id = v_remote.owner_user_id;

  insert into public.order_auto_remote_events (
    remote_contract_id,
    owner_user_id,
    event_type,
    metadata
  ) values (
    v_remote.id,
    v_remote.owner_user_id,
    'submitted_for_review',
    jsonb_build_object('signer_name', v_clean_name, 'buyer_email', v_clean_email)
  );

  return query select
    v_remote.id,
    v_remote.contract_id,
    v_remote.owner_user_id,
    v_now,
    coalesce(v_contract_data->>'estimateNo', ''),
    v_clean_email,
    v_contract_data;
end;
$$;

revoke all privileges on table public.order_auto_contracts from anon, authenticated;
revoke all privileges on table public.order_auto_document_counters from anon, authenticated;
revoke all privileges on table public.order_auto_remote_contracts from anon, authenticated;
revoke all privileges on table public.order_auto_remote_events from anon, authenticated;
revoke all privileges on table public.order_auto_admin_notifications from anon, authenticated;

grant select, insert, update, delete on table public.order_auto_contracts to authenticated;
grant select, delete on table public.order_auto_remote_contracts to authenticated;
grant select on table public.order_auto_remote_events to authenticated;
grant select, update, delete on table public.order_auto_admin_notifications to authenticated;

revoke all privileges on function public.set_order_auto_updated_at() from public, anon, authenticated;
revoke all privileges on function public.lock_submitted_order_auto_remote_link() from public, anon, authenticated;
revoke all privileges on function public.save_order_auto_contract(text, text, text, text, text, text, text, jsonb) from public, anon, authenticated;
revoke all privileges on function public.create_order_auto_remote_contract(text, text, text, timestamptz) from public, anon, authenticated;
revoke all privileges on function public.read_order_auto_remote_contract(text, text) from public, anon, authenticated;
revoke all privileges on function public.complete_order_auto_remote_contract(text, text, text, jsonb, text) from public, anon, authenticated;
revoke all privileges on function public.complete_order_auto_remote_contract_v2(text, text, text, jsonb, text, jsonb) from public, anon, authenticated;
revoke all privileges on function public.submit_order_auto_remote_contract_for_review(text, text, text, jsonb, text, jsonb) from public, anon, authenticated;

grant execute on function public.create_order_auto_remote_contract(text, text, text, timestamptz) to authenticated;
grant execute on function public.save_order_auto_contract(text, text, text, text, text, text, text, jsonb) to authenticated;
grant execute on function public.read_order_auto_remote_contract(text, text) to anon, authenticated;
grant execute on function public.complete_order_auto_remote_contract(text, text, text, jsonb, text) to anon, authenticated;
grant execute on function public.complete_order_auto_remote_contract_v2(text, text, text, jsonb, text, jsonb) to anon, authenticated;
grant execute on function public.submit_order_auto_remote_contract_for_review(text, text, text, jsonb, text, jsonb) to service_role;

alter table public.order_auto_contracts
  add column if not exists customer_pdf_path text,
  add column if not exists download_access_hash text,
  add column if not exists download_access_expires_at timestamptz,
  add column if not exists reviewed_at timestamptz,
  add column if not exists customer_confirmation_sent_at timestamptz,
  add column if not exists confirmation_email_status text;

alter table public.order_auto_remote_contracts
  add column if not exists customer_pdf_path text;

create unique index if not exists order_auto_contracts_download_access_hash_key
on public.order_auto_contracts (download_access_hash)
where download_access_hash is not null;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('order-auto-contract-files', 'order-auto-contract-files', false, 15728640, array['application/pdf'])
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.submit_order_auto_remote_contract_for_review(
  p_access_token text,
  p_passcode text,
  p_signer_name text,
  p_consent_items jsonb,
  p_signature_data_url text,
  p_customer_data jsonb
)
returns table(
  remote_id uuid,
  contract_id text,
  owner_user_id uuid,
  signed_at timestamptz,
  contract_number text,
  buyer_email text,
  contract_data jsonb
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_remote public.order_auto_remote_contracts%rowtype;
  v_now timestamptz := now();
  v_clean_name text := btrim(coalesce(p_signer_name, ''));
  v_customer jsonb := coalesce(p_customer_data, '{}'::jsonb);
  v_clean_zip text;
  v_clean_phone text;
  v_clean_email text;
  v_contract_data jsonb;
begin
  if p_access_token is null or p_access_token !~ '^[A-Za-z0-9_-]{43,128}$'
    or p_passcode is null or p_passcode !~ '^[0-9]{8}$' then
    return;
  end if;
  if jsonb_typeof(v_customer) <> 'object'
    or length(v_clean_name) < 1 or length(v_clean_name) > 120 then
    return;
  end if;

  v_clean_zip := regexp_replace(coalesce(v_customer->>'buyerZip', ''), '[^0-9]', '', 'g');
  v_clean_phone := regexp_replace(coalesce(v_customer->>'buyerPhone', ''), '[^0-9]', '', 'g');
  v_clean_email := btrim(coalesce(v_customer->>'buyerEmail', ''));
  if btrim(coalesce(v_customer->>'buyerAddress', '')) = ''
    or v_clean_zip !~ '^[0-9]{7}$'
    or v_clean_phone !~ '^[0-9]{10,11}$'
    or v_clean_email !~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$' then
    return;
  end if;
  if p_consent_items is null or jsonb_typeof(p_consent_items) <> 'array'
    or jsonb_array_length(p_consent_items) < 1 then
    return;
  end if;
  if p_signature_data_url is null or p_signature_data_url !~ '^data:image/png;base64,'
    or octet_length(p_signature_data_url) > 750000 then
    return;
  end if;

  select * into v_remote
  from public.order_auto_remote_contracts as remote
  where remote.access_token_hash = extensions.digest(convert_to(p_access_token, 'UTF8'), 'sha256')
  for update;
  if not found or v_remote.status in ('完了', '確認待ち', '取消')
    or v_remote.expires_at <= v_now
    or (v_remote.locked_until is not null and v_remote.locked_until > v_now)
    or extensions.crypt(p_passcode, v_remote.passcode_hash) <> v_remote.passcode_hash then
    return;
  end if;

  v_customer := jsonb_build_object(
    'buyerLastName', left(btrim(coalesce(v_customer->>'buyerLastName', '')), 60),
    'buyerFirstName', left(btrim(coalesce(v_customer->>'buyerFirstName', '')), 60),
    'buyerName', v_clean_name,
    'buyerKana', left(btrim(coalesce(v_customer->>'buyerKana', '')), 120),
    'buyerBirthday', left(btrim(coalesce(v_customer->>'buyerBirthday', '')), 20),
    'buyerZip', substr(v_clean_zip, 1, 3) || '-' || substr(v_clean_zip, 4),
    'buyerAddress', left(btrim(v_customer->>'buyerAddress'), 300),
    'buyerPhone', left(btrim(v_customer->>'buyerPhone'), 30),
    'buyerEmail', left(v_clean_email, 254),
    'buyerWorkplace', left(btrim(coalesce(v_customer->>'buyerWorkplace', '')), 200)
  );
  v_contract_data := v_remote.contract_data || v_customer;

  update public.order_auto_remote_contracts
  set contract_data = v_contract_data,
      status = '確認待ち',
      signer_name = v_clean_name,
      consent_items = p_consent_items,
      signature_data_url = p_signature_data_url,
      completed_at = v_now,
      customer_pdf_path = null,
      failed_attempts = 0,
      locked_until = null
  where id = v_remote.id;

  update public.order_auto_contracts
  set buyer_name = v_clean_name,
      buyer_email = v_clean_email,
      status = '確認待ち',
      completed_at = null,
      customer_pdf_path = null,
      download_access_hash = null,
      download_access_expires_at = null,
      reviewed_at = null,
      customer_confirmation_sent_at = null,
      confirmation_email_status = null,
      data = jsonb_set(
        jsonb_set(data || v_customer, '{contractStatus}', '"確認待ち"'::jsonb, true),
        '{remoteStatus}', '"確認待ち"'::jsonb, true
      )
  where id = v_remote.contract_id and user_id = v_remote.owner_user_id;

  insert into public.order_auto_remote_events (remote_contract_id, owner_user_id, event_type, metadata)
  values (
    v_remote.id,
    v_remote.owner_user_id,
    'submitted_for_review',
    jsonb_build_object('signer_name', v_clean_name, 'buyer_email', v_clean_email)
  );

  return query select
    v_remote.id,
    v_remote.contract_id,
    v_remote.owner_user_id,
    v_now,
    coalesce(v_contract_data->>'estimateNo', ''),
    v_clean_email,
    v_contract_data;
end;
$$;

revoke all privileges on function public.submit_order_auto_remote_contract_for_review(text, text, text, jsonb, text, jsonb)
from public, anon, authenticated;
grant execute on function public.submit_order_auto_remote_contract_for_review(text, text, text, jsonb, text, jsonb)
to service_role;

create or replace function public.lock_submitted_order_auto_remote_link()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status = '確認待ち' and old.status is distinct from new.status then
    new.expires_at = least(new.expires_at, now());
  end if;
  return new;
end;
$$;

drop trigger if exists order_auto_remote_contracts_lock_submitted_link
on public.order_auto_remote_contracts;
create trigger order_auto_remote_contracts_lock_submitted_link
before update of status on public.order_auto_remote_contracts
for each row execute function public.lock_submitted_order_auto_remote_link();

revoke all privileges on function public.lock_submitted_order_auto_remote_link()
from public, anon, authenticated;


